# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='admin3_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='postal_codes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
